BatteryCondition/Models/GetBatteryPackViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BatteryConditionInventory.Models.ViewModels;
using BatteryConditionInventory.Core.Interfaces;
using BatteryConditionInventory.Core.Entities;
using BatteryConditionInventory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;

namespace BatteryConditionInventory.Models
{
    public static class GetBatteryPackViewModel
    {
        
        public static BatteryPackViewModel GetViewModel(BatteryContext context, int Id)
        {
            BatteryPackViewModel viewModel = new BatteryPackViewModel();
            viewModel.Date = context.BatteryPacks.Include(ad => ad.AddressByDate).First(bp=>bp.Id==1).AddressByDate.DateTime.Date;
            viewModel.BatteryConditionBatteryPacksList = context.BatteryPacks.Include(bcbp => bcbp.BatteryConditionBatteryPacks)
                .First(bp => bp.Id == Id).BatteryConditionBatteryPacks.ToList();
            

            foreach (BatteryConditionBatteryPack b in viewModel.BatteryConditionBatteryPacksList)
            {
                viewModel.BatteryConditionList.Add(b.BatteryCondition);
            }
            return viewModel;
        }
    }
}

BatteryCondition/Models/GetViewModels/GetBatteryConditionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BatteryCondition.Models.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace BatteryCondition.Models.GetViewModels
{
    public static class GetBatteryConditionViewModel
    {
        public static BatteryConditionViewModel GetViewModel(BatteryContext context, int Id)
        {
            var batteryCondition = context.BatteryConditions.Include(bc => bc.BatteryModel.BatteryBrand)
                .Include(bc =>bc.AddressByDates)
                    .ThenInclude(ad=>ad.House.Street)
                .Include(bc => bc.BatteryConditionBatteryPacks)
                    .ThenInclude(bp=>bp.BatteryPack.AddressByDate.House.Street)
                .Include(bc => bc.CapacityByDates)
                .FirstOrDefault(bc => bc.BatteryConditionId == Id);

            BatteryConditionViewModel batteryConditionViewModel = new BatteryConditionViewModel
            {
                BatteryLocalId = batteryCondition.BatteryLocalId,
                BatteryModelName = batteryCondition.BatteryModel.BatteryModelName,
                BatteryBrandName = batteryCondition.BatteryModel.BatteryBrand.BatteryBrandName,
                LastBatteryPack = batteryCondition.BatteryConditionBatteryPacks.LastOrDefault().BatteryPack,
                BatteryModelCapacity = batteryCondition.BatteryModel.BatteryCapacity,
                LastDate = batteryCondition.AddressByDates.LastOrDefault().Date,
                LastCapacity = batteryCondition.CapacityByDates.LastOrDefault()?.Capacity ?? 
                                   0,
                LastCapacityDate = batteryCondition.CapacityByDates.LastOrDefault()?.Date ??
                                   batteryCondition.AddressByDates.LastOrDefault().Date.Date,

                AddressByDates = batteryCondition.AddressByDates.ToList(),
                CapacityByDates = batteryCondition.CapacityByDates.ToList()
            };

            return batteryConditionViewModel;
        }
    }
}

BatteryCondition/Models/GetViewModels/GetBatteryPackViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BatteryCondition.Models.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace BatteryCondition.Models.GetViewModels
{
    public static class GetBatteryPackViewModel
    {
        public static BatteryPackViewModel GetViewModel(BatteryContext context, int Id)
        {
            var batteryPack = context.BatteryPacks
                .Include(bcbp => bcbp.BatteryConditionBatteryPacks)
                .ThenInclude(bc => bc.BatteryCondition.BatteryModel.BatteryBrand)
                .Include(q=>q.BatteryConditionBatteryPacks).ThenInclude(w=>w.BatteryCondition.AddressByDates)            
                .Include(ad => ad.AddressByDate.House.Street)
                .First(bp=>bp.BatteryPackId==Id);
            
            BatteryPackViewModel batteryPackViewModel = new BatteryPackViewModel();
            batteryPackViewModel.Address = batteryPack.AddressByDate.House.Street.StreetName + " " 
                                            + batteryPack.AddressByDate.House.HouseNumber;
            batteryPackViewModel.Date = batteryPack.AddressByDate.Date.Date;

            batteryPackViewModel.BatteryConditions = new List<BatteryCondition>();
            //batteryPackViewModel.BatteryConditionDates = new List<DateTime>();
            foreach (var bp in batteryPack.BatteryConditionBatteryPacks)
            {
                batteryPackViewModel.BatteryConditions.Add(bp.BatteryCondition);
                //batteryPackViewModel.BatteryConditionDates.Add(bp.BatteryCondition.AddressByDates.Last().DateTime.Date);
            }
            return batteryPackViewModel;
        }
    }
}

BatteryCondition/Controllers/CreateController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BatteryCondition.Models;
using BatteryCondition.Models.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace BatteryCondition.Controllers
{
    public class CreateController : Controller
    {
        BatteryContext db; // Не нравится мне это решение, как и логика добавления в конроллере CreateBatteryCondition

        public CreateController(BatteryContext context)
        {
            db = context;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult CreateBatteryCondition()
        {
            CreateBatteryConditionViewModel createBattery = new CreateBatteryConditionViewModel();
            createBattery.BatteryModel = new BatteryModel();
            createBattery.BatteryModels = new List<BatteryModel>();
            
            createBattery.BatteryModels = db.BatteryModels.ToList();
            createBattery.BatteryConditionBatteryPack = new BatteryConditionBatteryPack();
            createBattery.CapacityByDate = new CapacityByDate();
            
            return View(createBattery);
        }
        [HttpPost]
        public IActionResult CreateBatteryCondition(CreateBatteryConditionViewModel createBattery)
        {
            Models.BatteryCondition batteryCondition = new Models.BatteryCondition();
            batteryCondition.AddressByDates = new List<AddressByDate>();
            // Проверка на существование уже записи в таблицах House и Street
            if (db.Houses.ToList().Exists(h=>h.HouseNumber== createBattery.AddressByDate.House.HouseNumber)&&
                (db.Houses.Include(s=>s.Street).ToList().Exists(h => h.Street.StreetName == createBattery.AddressByDate.House.Street.StreetName)))
            {
                batteryCondition.AddressByDates.Add(new AddressByDate
                {
                    House = db.Houses.ToList().Find(h=>h.HouseNumber== createBattery.AddressByDate.House.HouseNumber &&
                        h.Street.StreetName== createBattery.AddressByDate.House.Street.StreetName),
                    BatteryCondition = batteryCondition,
                    Date = DateTime.Today
                });
            }
            else
            {
                batteryCondition.AddressByDates.Add(
                new AddressByDate
                {
                    House = createBattery.AddressByDate.House,
                    BatteryCondition = batteryCondition,
                    Date = DateTime.Today
                }
                );
            }         
            
            batteryCondition.BatteryLocalId = createBattery.BatteryLocalId;
            batteryCondition.BatteryModelId = createBattery.BatteryModel.BatteryModelId;
            // batteryCondition.CapacityByDates.Add(createBattery.CapacityByDate);
            db.BatteryConditions.Add(batteryCondition);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BatteryCondition/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BatteryCondition.Models;
using BatteryCondition.Models.ViewModels;
using Microsoft.EntityFrameworkCore;
using BatteryCondition.Models.GetViewModels;


namespace BatteryCondition.Controllers
{
    public class HomeController : Controller
    {
        BatteryContext db;
        public HomeController(BatteryContext context)
        {
            db = context;
        }
        public IActionResult Index()
        {
            IndexViewModel indexViewModel = new IndexViewModel
            {
                BatteryModels = db.BatteryModels.Include(bb => bb.BatteryBrand),
                BatteryPacks = db.BatteryPacks.Include(bp => bp.BatteryConditionBatteryPacks)
                .ThenInclude(bcbp => bcbp.BatteryCondition)
                .ThenInclude(bc => bc.BatteryModel)
                .ThenInclude(bm => bm.BatteryBrand)
                .Include(ad => ad.AddressByDate).ThenInclude(h => h.House).ThenInclude(s => s.Street)
            };

            return View(indexViewModel);
        }

        [HttpGet]
        public IActionResult GetBatteryConditionsByBatteryModel(int id)
        {
            BatteryModel batteryModel = db.BatteryModels.Include(bb => bb.BatteryBrand)
                .ToList().Find(bm => bm.BatteryModelId == id);
            ViewBag.BatteryModel = batteryModel;
            return View(db.BatteryConditions.Include(ad => ad.AddressByDates)
                .ThenInclude(h => h.House)
                .ThenInclude(s => s.Street)
                .ToList().FindAll(b => b.BatteryModel == batteryModel)
                );
        }
        [HttpGet]
        public IActionResult GetBatteryCondition(int id)
        {
            Models.BatteryCondition batteryCondition = new Models.BatteryCondition();
            batteryCondition = db.BatteryConditions
                .Include(ad => ad.AddressByDates).ThenInclude(h => h.House).ThenInclude(s => s.Street)
                .Include(bm => bm.BatteryModel).ThenInclude(bb => bb.BatteryBrand)
                .Include(bcbp => bcbp.BatteryConditionBatteryPacks) //пустая таблица сейчас при генерации!
                    .ThenInclude(bp => bp.BatteryPack).ThenInclude(ad => ad.AddressByDate).ThenInclude(h => h.House).ThenInclude(s => s.Street)
                .Include(cd => cd.CapacityByDates)
                .First(i => i.BatteryConditionId == id);
            return View(batteryCondition);
        }

        [HttpGet]
        public IActionResult GetBatteryPack(int id)
        {
            BatteryPack batteryPack = new BatteryPack();
            batteryPack = db.BatteryPacks.Include(ad => ad.AddressByDate).ThenInclude(h => h.House).ThenInclude(s => s.Street)
                .Include(b => b.BatteryConditionBatteryPacks).ThenInclude(bcbp => bcbp.BatteryCondition).First(bp => bp.BatteryPackId == id);
            return View(batteryPack);
        }
        [HttpGet]
        public IActionResult GetBatteryPackTest(int Id)
        {
            return View(GetBatteryPackViewModel.GetViewModel(db, Id));
        }
        
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BatteryCondition/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

BatteryCondition/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BatteryCondition/Views/Home/GetBatteryCondition.cshtml
@model BatteryCondition
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>Состояние АКБ</title>
</head>
<body>
    <!-- <h3>Состояние АКБ производителя  модели  Номер </h3> -->
    <table>
        <tr>
            <td>Номер АКБ</td>
            <td>Модель АКБ</td>
            <td>Адрес</td>
            <td>Дата установки</td>
            <td>Емкость</td>
            <td>Батарейный блок</td>
        </tr>
        <tr>
            <td>@Model.BatteryLocalId</td>
            <td>@Model.BatteryModel.BatteryBrand.BatteryBrandName @Model.BatteryModel.BatteryModelName</td>
            <td>@Model.AddressByDates.LastOrDefault()?.House.Street.StreetName @Model.AddressByDates.LastOrDefault()?.House.HouseNumber</td>
            <td>@Model.AddressByDates.LastOrDefault()?.Date.Date</td>
            <td></td>
            <td><a href="/Home/GetBatteryPack/@Model.BatteryConditionBatteryPacks.LastOrDefault()?.BatteryPackId">
                @Model.BatteryConditionBatteryPacks.LastOrDefault()?.BatteryPack.AddressByDate.House.Street.StreetName
                @Model.BatteryConditionBatteryPacks.LastOrDefault()?.BatteryPack.AddressByDate.House.HouseNumber </a>
            </td>
        </tr>
    </table>

</body>
</html>

BatteryCondition/Views/Home/GetBatteryConditionsByBatteryModel.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model ICollection<BatteryCondition>
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Список АКБ модели: @ViewBag.BatteryModel.BatteryModelName</title>
</head>
<body>
    <h3>Список АКБ производителя @ViewBag.BatteryModel.BatteryBrand.BatteryBrandName модели @ViewBag.BatteryModel.BatteryModelName </h3>
    <table>
        <tr>
            <td>Номер АКБ</td>
            <td>Адрес</td>
            <td>Дата установки</td>
        </tr>

        @foreach (var battery in Model)
        {
        <tr>
            <td>
                <a href="~/Home/GetBatteryCondition/@battery?.BatteryConditionId">
                    @battery.BatteryLocalId
                </a>
            </td>
            <td>@battery.AddressByDates.LastOrDefault()?.House.Street.StreetName @battery.AddressByDates.LastOrDefault()?.House.HouseNumber</td>
            <td>@battery.AddressByDates.LastOrDefault()?.Date</td>
        </tr>
        }
        </table>

</body>
</html>

BatteryCondition/Views/Home/GetBatteryPack.cshtml
@using BatteryCondition.Models.ViewModels
@{
    Layout = null;
}
@model BatteryPack

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GetBatteryPack</title>
</head>
<body>
    <table>
        <tr>            
            <td>Адрес</td>
            <td>Дата установки</td>            
        </tr>
        <tr>            
            <td>@Model.AddressByDate.House.Street.StreetName @Model.AddressByDate.House.HouseNumber</td>
            <td>@Model.AddressByDate.Date.Date</td>            
        </tr>
    </table>
    
</body>
</html>

BatteryCondition/Views/Home/GetBatteryPackTest.cshtml
@using BatteryCondition.Models.ViewModels;
@using BatteryCondition.Models;
@model BatteryPackViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GetBatteryPackTest</title>
</head>
<body>
    <table>
        <tr>
            <td>Адрес</td>
            <td>Дата установки</td>
            
        </tr>
        <tr>
            <td>@Model.Address</td>
            <td>@Model.Date</td>
            
        </tr>
    </table>
    <table>
        <tr>
            <td>Модель АКБ</td>
            <td>Производитель</td>
            <td>Номер АКБ</td>
            <td>Дата установки</td>
        </tr>
        @foreach (var pack in Model.BatteryConditions)
        {
        <tr>
            <td>
                @pack.BatteryModel.BatteryModelName
            </td>
            <td>
                @pack.BatteryModel.BatteryBrand.BatteryBrandName
            </td>
            <td>@pack.BatteryLocalId</td>
            <td>@pack.AddressByDates.Last().Date.Date</td>
        </tr>
    }
    </table>
</body>
</html>

BatteryCondition/Views/Home/Index.cshtml
@using BatteryConditionInventory.Models.ViewModels
@using BatteryConditionInventory.Core.Entities
@model IndexViewModel
@{
    // ViewData["Title"] = "Список моделей АКБ";
    Layout = null;
}
<!DOCTYPE html>

<hnml>
    <title>Стартовая страница</title>
    <body>
        <h3>Модели АКБ</h3>
        <table>
            <tr>
                <td>Модель</td>
                <td>Паспортная емкость</td>
                <td>Производитель АКБ</td>
            </tr>
            @foreach (var modelBattery in Model.BatteryModels)
            {
                <tr>
                    <td>
                        <a href="~/Home/GetBatteryConditionsByBatteryModel/@modelBattery.Id">
                            @modelBattery.BatteryModelName
                        </a>
                    </td>
                    <td>@modelBattery.BatteryCapacity</td>
                    <td>@modelBattery.BatteryBrand.BatteryBrandName</td>

                </tr>
            }
        </table>
        <h3>Батарейные блоки</h3>
        <table>
            <tr>
                <td>Батарейный блок</td>
                <td>Модель АКБ</td>
                <td>Кол-во АКБ</td>
            </tr>
            @foreach (var pack in Model.BatteryPacks)
            {
                <tr>
                    <td>
                        <a href="/Home/GetBatteryPack/@pack.Id">
                            @pack.AddressByDate.House.Street.StreetName @pack.AddressByDate.House.HouseNumber
                        </a>
                    </td>
                    <td>
                        @pack.BatteryConditionBatteryPacks.Last().BatteryCondition.BatteryModel.BatteryBrand.BatteryBrandName
                    @pack.BatteryConditionBatteryPacks.Last().BatteryCondition.BatteryModel.BatteryModelName
                </td>
                <td>@pack.BatteryConditionBatteryPacks.Count</td>
            </tr>
        }
        </table>
        <h3>Добавить АКБ</h3>

        @Html.ActionLink("Добавление АКБ", "CreateBatteryCondition", "Create")
    </body>

</hnml>